//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExternalClient.ServiceA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", ConfigurationName="ServiceA.IAdmin")]
    public interface IAdmin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IAdmin/AdminOperation1", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IAdmin/AdminOperation1Response")]
        string AdminOperation1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IAdmin/AdminOperation1", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IAdmin/AdminOperation1Response")]
        System.Threading.Tasks.Task<string> AdminOperation1Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IAdmin/AdminOperation2", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IAdmin/AdminOperation2Response")]
        string AdminOperation2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IAdmin/AdminOperation2", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IAdmin/AdminOperation2Response")]
        System.Threading.Tasks.Task<string> AdminOperation2Async();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminChannel : ExternalClient.ServiceA.IAdmin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminClient : System.ServiceModel.ClientBase<ExternalClient.ServiceA.IAdmin>, ExternalClient.ServiceA.IAdmin {
        
        public AdminClient() {
        }
        
        public AdminClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AdminOperation1() {
            return base.Channel.AdminOperation1();
        }
        
        public System.Threading.Tasks.Task<string> AdminOperation1Async() {
            return base.Channel.AdminOperation1Async();
        }
        
        public string AdminOperation2() {
            return base.Channel.AdminOperation2();
        }
        
        public System.Threading.Tasks.Task<string> AdminOperation2Async() {
            return base.Channel.AdminOperation2Async();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", ConfigurationName="ServiceA.IServiceA")]
    public interface IServiceA {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IServiceA/Operation1", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IServiceA/Operation1Response")]
        string Operation1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IServiceA/Operation1", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IServiceA/Operation1Response")]
        System.Threading.Tasks.Task<string> Operation1Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IServiceA/Operation2", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IServiceA/Operation2Response")]
        string Operation2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IServiceA/Operation2", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IServiceA/Operation2Response")]
        System.Threading.Tasks.Task<string> Operation2Async();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAChannel : ExternalClient.ServiceA.IServiceA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAClient : System.ServiceModel.ClientBase<ExternalClient.ServiceA.IServiceA>, ExternalClient.ServiceA.IServiceA {
        
        public ServiceAClient() {
        }
        
        public ServiceAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Operation1() {
            return base.Channel.Operation1();
        }
        
        public System.Threading.Tasks.Task<string> Operation1Async() {
            return base.Channel.Operation1Async();
        }
        
        public string Operation2() {
            return base.Channel.Operation2();
        }
        
        public System.Threading.Tasks.Task<string> Operation2Async() {
            return base.Channel.Operation2Async();
        }
    }
}
