//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.localhost {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="localhost.IHelloIndigoService")]
    public interface IHelloIndigoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloIndigoService/HelloIndigo", ReplyAction="http://tempuri.org/IHelloIndigoService/HelloIndigoResponse")]
        string HelloIndigo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloIndigoService/HelloIndigo", ReplyAction="http://tempuri.org/IHelloIndigoService/HelloIndigoResponse")]
        System.Threading.Tasks.Task<string> HelloIndigoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelloIndigoServiceChannel : Client.localhost.IHelloIndigoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloIndigoServiceClient : System.ServiceModel.ClientBase<Client.localhost.IHelloIndigoService>, Client.localhost.IHelloIndigoService {
        
        public HelloIndigoServiceClient() {
        }
        
        public HelloIndigoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloIndigoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloIndigoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloIndigoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloIndigo() {
            return base.Channel.HelloIndigo();
        }
        
        public System.Threading.Tasks.Task<string> HelloIndigoAsync() {
            return base.Channel.HelloIndigoAsync();
        }
    }
}
