//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientForRoutingService.HelloIndigoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloIndigoService.IHelloIndigoService")]
    public interface IHelloIndigoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloIndigoService/HelloIndigo", ReplyAction="http://tempuri.org/IHelloIndigoService/HelloIndigoResponse")]
        string HelloIndigo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHelloIndigoService/HelloIndigo", ReplyAction="http://tempuri.org/IHelloIndigoService/HelloIndigoResponse")]
        System.Threading.Tasks.Task<string> HelloIndigoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHelloIndigoServiceChannel : ClientForRoutingService.HelloIndigoService.IHelloIndigoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloIndigoServiceClient : System.ServiceModel.ClientBase<ClientForRoutingService.HelloIndigoService.IHelloIndigoService>, ClientForRoutingService.HelloIndigoService.IHelloIndigoService {
        
        public HelloIndigoServiceClient() {
        }
        
        public HelloIndigoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloIndigoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloIndigoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloIndigoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloIndigo() {
            return base.Channel.HelloIndigo();
        }
        
        public System.Threading.Tasks.Task<string> HelloIndigoAsync() {
            return base.Channel.HelloIndigoAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloIndigoService.IService2")]
    public interface IService2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/Hello", ReplyAction="http://tempuri.org/IService2/HelloResponse")]
        string Hello(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/Hello", ReplyAction="http://tempuri.org/IService2/HelloResponse")]
        System.Threading.Tasks.Task<string> HelloAsync(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/Hello2", ReplyAction="http://tempuri.org/IService2/Hello2Response")]
        string Hello2(string @string);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/Hello2", ReplyAction="http://tempuri.org/IService2/Hello2Response")]
        System.Threading.Tasks.Task<string> Hello2Async(string @string);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService2Channel : ClientForRoutingService.HelloIndigoService.IService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service2Client : System.ServiceModel.ClientBase<ClientForRoutingService.HelloIndigoService.IService2>, ClientForRoutingService.HelloIndigoService.IService2 {
        
        public Service2Client() {
        }
        
        public Service2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Hello(string s) {
            return base.Channel.Hello(s);
        }
        
        public System.Threading.Tasks.Task<string> HelloAsync(string s) {
            return base.Channel.HelloAsync(s);
        }
        
        public string Hello2(string @string) {
            return base.Channel.Hello2(@string);
        }
        
        public System.Threading.Tasks.Task<string> Hello2Async(string @string) {
            return base.Channel.Hello2Async(@string);
        }
    }
}
